version: 2

sources:
  - name: jaffle_shop
    database: ccastro_sandbox
    tables:
      - name: customers
      - name: orders
  - name: stripe
    database: ccastro_sandbox
    tables:
      - name: payment
